# Generated by Django 5.0.6 on 2026-07-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated ingredient list, shown on the product detail page.",
            ),
        ),
    ]
