# Generated by Django 5.2.16 on 2026-08-19 10:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bulk_min_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                default=2,
                help_text="Quantity at which bulk_price kicks in, e.g. 2.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bulk_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-unit price once bulk_min_quantity is reached, e.g. 110.00.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
