# Generated by Django 5.2.16 on 2026-08-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_kunafa_rakhi_pricing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["display_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
