# Generated by Django 5.2.16 on 2026-07-31 19:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_address_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="abandoned_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="referral_discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
