# Generated by Django 5.2.16 on 2026-08-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_abandoned_reminder_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_promo_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
