# Generated by Django 5.2.16 on 2026-08-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_gift_message_order_is_gift_orderstatushistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="applied_promo_code",
        ),
    ]
