# Generated by Django 5.2.17 on 2026-08-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_cart_applied_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="placed_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
