# Generated by Django 5.0.6 on 2026-07-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("manual", "UPI / Bank Transfer"),
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                ],
                max_length=20,
            ),
        ),
    ]
