# Generated by Django 5.2.16 on 2026-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_gateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="utr_reference",
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
