# Generated by Django 5.2.17 on 2026-09-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageview",
            name="city",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pageview",
            name="country",
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name="pageview",
            name="region",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["created_at", "city"], name="analytics_p_created_fb6f2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["created_at", "region"], name="analytics_p_created_05caa2_idx"
            ),
        ),
    ]
